name: Continuous Integration

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: |
          npx prettier --check .
          npx eslint .

      - name: Run TypeScript type checking
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Build package
        run: npm run build

      - name: Check package contents
        run: |
          echo "Package contents:"
          ls -la dist/
          echo "Package size:"
          du -sh dist/
